### ISSUE TITLE
Repo instead of manual installation? :-)

### ISSUE THREAD

**Issue by marzdrel** [filiptepper/ansible-docker#1]
Docker actually maintains updated APT repository for Ubuntu, which can ease maintenance in the long term...

```
tasks:
- name: add custom repositories
  apt_repository: repo='{{ item }}' state=present
  with_items:
    - deb https://get.docker.io/ubuntu docker main
- name: docker repo key
  apt_key: id=D8576A8BA88D21E9 keyserver=hkp://keyserver.ubuntu.com
```
